ChapterCreated title@Text: Ihr neues Kapitel, #{title}, erstellt wurde.
ChapterUpdated title@Text: Das Kapitel #{title} wurde erfolgreich aktualisiert.
ChapterDeleted title@Text: Das Kapitel #{title} wurde gelöscht.
ChapterDeleteHeader title@Text: Wollen Sie wirklich, um das Kapitel #{title} löschen?
ChapterUpdateHeader title@Text: Update Kapitel #{title}
ChapterPleaseCorrectEntry: Ihre eingereichten Eingabe hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
ChapterNotFound id@Int: Das Kapitel ##{id} konnte nicht gefunden werden.
ChapterDelete: Delete Kapitel
ChapterUpdate: Update Kapitel
ChapterNew: Erstellen Sie ein neues Kapitel
ChapterNewHeader: Neues Kapitel
ChapterHeader title@Text: Chapter #{title}
ChapterListHeader: Chapters
Books: Bücher
BookCreated title@Text: Ihr neues Buch, #{title}, erstellt wurde.
BookUpdated title@Text: Das Buch #{title} wurde erfolgreich aktualisiert.
BookDeleted title@Text: Das Buch #{title} wurde gelöscht.
BookListHeader: Buch-Liste
BookDeleteHeader title@Text: Wollen Sie wirklich, das Buch #{title} löschen?
BookUpdateHeader title@Text: Update book #{title}
BookNotFound id@Int: Das Buch ##{id} konnte nicht gefunden werden.
BookDelete: Buch löschen
BookEdit: Edit Buch
BookUpdate: Update Buch
BookNew: Erstellen Sie ein neues Buch
BookNewHeader: Neues Buch
BreadcrumbBookUpdate bookId@Text: Update Book ##{bookId}
BreadcrumbBookDelete bookId@Text: Löschen Book ##{bookId}
BreadcrumbChapter chapterId@Text: Chapter ##{chapterId}
BreadcrumbChapterInsert bookId@Text: Kapitel hinzufügen, um Book ##{bookId}
BreadcrumbChapterUpdate chapterId@Text: Update Chapter ##{chapterId}
BreadcrumbChapterDelete chapterId@Text: Kapitel löschen ##{chapterId}
BreadcrumbTranslationInsert cardId@Text: In Translation to Card ##{cardId}
BreadcrumbTranslationUpdate translationId@Text: Update Translation ##{translationId}
BreadcrumbTranslationDelete translationId@Text: Löschen Translation ##{translationId}
BreadcrumbCardChapterAdd chapterId@Text: In Card Kapitel ##{chapterId}
BreadcrumbCardChapterInsert cardId@Text chapterId@Text: Schließen Kapitel ##{chapterId} und Card ##{cardId}
BreadcrumbCardChaptersDelete cardId@Text: Unlink Card ##{cardId} aus den Kapiteln
BreadcrumbCard cardId@Text: Card ##{cardId}
BreadcrumbCardInsert cardId@Text: Insert Card ##{cardId}
BreadcrumbCardUpdate cardId@Text: Update Card ##{cardId}
BreadcrumbCardDelete cardId@Text: Löschen Card ##{cardId}
TranslationCreated title@Text: Ihr neuer Übersetzung, #{title}, erstellt wurde.
TranslationUpdated title@Text: Die Übersetzung #{title} wurde erfolgreich aktualisiert.
TranslationDeleted title@Text: Die Übersetzung #{title} wurde gelöscht.
TranslationDeleteHeader title@Text: Wollen Sie wirklich die Übersetzung #{title} löschen?
TranslationUpdateHeader title@Text: Update translation #{title}
TranslationPleaseCorrectEntry: Ihre eingereichten Eingabe hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
TranslationNotFound id@Int: Die Übersetzung ##{id} konnte nicht gefunden werden.
TranslationDelete: Delete-Übersetzung
TranslationEdit: Edit-Übersetzung
TranslationUpdate: Update-Übersetzung
TranslationNew: Erstellen einer neuen Übersetzung
TranslationNewHeader: Neue Übersetzung
CardCreated title@Text: Ihre neue Karte, #{title}, erstellt wurde.
CardUpdated title@Text: Die Karte #{title} wurde erfolgreich aktualisiert.
CardDeleted title@Text: Die Karte #{title} wurde gelöscht.
CardDeleteHeader title@Text: Wollen Sie wirklich die Karte #{title} löschen?
CardUpdateHeader title@Text: Update-Karte #{title}
CardPleaseCorrectEntry: Ihre eingereichten Eingabe hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
CardNotFound id@Int: Die Karte ##{id} konnte nicht gefunden werden.
CardDelete: Delete-Karte
CardEdit: Edit-Karte
CardUpdate: Update-Karte
CardNew: Erstellen Sie eine neue Karte
CardNewHeader: Neue Karte
CardSearchHeader title@Text: Search for cards containing `#{title}'
CardOrphanedHeader: Verwaiste Cards
CardSearch: Suche Karte
CardChapterSearchHeader: Suche Karten zu diesem Kapitel hinzuzufügen
FieldSearchCard: Suche Karte
CardFoundInTheFollowingChapters: Gehört zu
NotTrustedUser: Du bist nicht ein vertrauenswürdiger Benutzer.
TooltipVocabtrainCardShow: KARTE
CardChapterCreated: Erfolgreich Karte Kapitel.
CardChapterInsert: In-Karte
CardChapterAddHeader title@Text: Karten mit dem Stichwort #{title}
CardChaptersDeleteHeader title@Text: Entfernen Sie die Karte, #{title}, aus den Kapiteln
CardChaptersDelete: Links löschen
CardUpdateToDuplicate: Eine Karte mit dieser Beschreibung bereits vorhanden, so können Sie nicht ändern diese Karte an einem Duplikat.
CardChapterAdded title@Text: As the card #{title} already existed, we've merely added it to this chapter.
CardChaptersDeleted title@Text: Erfolgreich card #{title} von ausgewählten Kapiteln entfernt.
TooltipVocabtrainTranslationUpdateR: Update Translation
TooltipVocabtrainTranslationDeleteR: Delete Übersetzung
TooltipTatoebaQueryR: Finden Beispielsätze
TooltipVocabtrainCardUpdate: Update-Karte
TooltipVocabtrainCardDelete: Delete-Karte
TooltipVocabtrainBookUpdateR: Update Buch
TooltipVocabtrainBookDeleteR: Buch löschen
TooltipVocabtrainChapterUpdateR: Update Kapitel
TooltipVocabtrainChapterDeleteR: Kapitel löschen
CardTypeNone:
CardTypeTransitive: trans.
CardTypeIntransitive: intr.
CardTypeReflexive: Refl.
CardTypeGodanDoushi: 五 段 动词
CardTypeIchidanDoushi: 一段 动词
CardTypeIrregularDoushi: irreg. 動詞
CardTypeComparative: comp.
CardTypeSuperlative: super
CardTypeNaAdjective: ナ
CardTypeIAdjective: イ
CardTypePreposition: prep.
CardTypePostposition: POSTP.
CardTypeParticle: Teil.
CardTypeFeminine: fem.
CardTypeMasculine: mas.
CardTypeNeuter: neu.
CardTypeFemininePlural: fem.pl.
CardTypeMasculinePlural: mas.pl.
CardTypeNeuterPlural: neu.pl.
CardTypeUnknown: Unknown
CardTypeVerb: Verb
CardTypeAdjective: Adjektiv
CardTypeAdverb: Adverb
CardTypeAdposition: Adposition
CardTypeConjugation: Konjugation
CardTypeAbbreviation: Abkürzung
CardTypeSaw: Saw
CardTypeNoun: Nomen
CardHeader title@Text: Betrachte Karte `#{title}'
VocabManipulationPermissionDenied: Sie müssen sich um Änderungen vorzunehmen.
FieldLanguage: Sprache
FieldName: Name
FieldVolume: Volume
FieldChapters: Chapters
FieldComment: Kommentar
FieldTranslation: Translation
FieldScript: Script
FieldScriptComment: Script Kommentar
FieldSpeech: Speech
FieldSpeechComment: Speech Kommentar
FieldCardType: Typ
FieldCardTypePrimary: Primary Type
FieldCardTypeSecondary: Secondary Type
FieldCardTypeTertiary: Tertiär Typ
Lang_eng: Englisch
Lang_epo: Esperanto
Lang_fra: Französisch
Lang_deu: Deutsch
Lang_jpn: Japanese
Lang_spa: Spanisch
Lang_tur: Turkish
Lang_por: Portugiesisch
Lang_ita: Italienisch
Lang_heb: Hebrew
Lang_rus: Russian
Lang_pol: Polnisch
Lang_cmn: Chinese
Lang_ber: Berber
Lang_nld: Dutch
Lang_hun: Hungarian
Lang_ukr: Ukrainisch
Lang_nds: Low Saxon
Lang_pes: Persian
Lang_ara: Arabisch
Lang_dan: Danish
Lang_isl: Icelandic
Lang_lat: Latin
Lang_swe: Swedish
Lang_jbo: Lojban
Lang_fin: Finnisch
Lang_srp: Serbian
Lang_vie: Vietnamese
Lang_lit: Litauisch
Lang_tlh: Klingon
Lang_bul: Bulgarisch
Lang_tgl: Tagalog
Lang_hin: Hindi
Lang_uig: Uiguren
Lang_cat: Katalanisch
Lang_ces: Tschechien
Lang_wuu: Shanghainese
Lang_glg: Galizisch
Lang_ina: Interlingua
Lang_ell: Neugriechisch
Lang_ido: Ido
Lang_nob: Norwegisch (Bokmål)
Lang_bel: Weißrussisch
Lang_ron: Rumänisch
Lang_yue: Kantonesisch
Lang_mar: Marathi
Lang_oci: Occitan
Lang_hrv: Kroatisch
Lang_ind: Indonesian
Lang_tat: Tatar
Lang_eus: Basque
Lang_lzh: Literary chinesischen
Lang_kaz: Kasachisch
Lang_toki: Toki Pona
Lang_urd: Urdu
Lang_kor: Korean
Lang_orv: Old East Slavic
Lang_afr: Afrikaans
Lang_zsm: Malay
Lang_avk: Kotava
Lang_slk: Slovak
Lang_xal: Kalmyk
Lang_mal: Malayalam
Lang_non: Norwegian (Nynorsk)
Lang_est: Estnisch
Lang_arz: Ägyptisch-Arabisch
Lang_lvs: Lettisch
Lang_vol: Volapük
Lang_bre: Breton
Lang_yid: Jiddisch
Lang_gla: Schottisch-Gälisch
Lang_mon: Mongolisch
Lang_hsb: Obersorbisch
Lang_dsb: Niedersorbisch
Lang_gle: Irish
Lang_kur: Kurdisch
Lang_cym: Welsh
Lang_que: Quechua
Lang_ile: Interlingue
Lang_kat: Georgian
Lang_sqi: Albanisch
Lang_uzb: Usbekisch
Lang_tha: Thai
Lang_oss: ossetischen
Lang_swh: Swahili
Lang_ang: Old English
Lang_nov: Novial
Lang_qya: Quenya
Lang_bos: Bosnisch
Lang_xho: Xhosa
Lang_fry: Frisian
Lang_slv: Slowenisch
Lang_lld: Ladin
Lang_tpi: Tok Pisin
Lang_lad: Ladino
Lang_tel: Telegu
Lang_cycl: CycL
Lang_ast: asturischen
Lang_ben: Bengali
Lang_acm: Iraqi Arabic
Lang_tpw: Old Tupi
Lang_pms: Piemontese
Lang_hye: Armenian
Lang_cha: Chamorro
Lang_tgk: tadschikischen
Lang_ewe: Ewe
Lang_mlg: Malagasy
Lang_pnb: Punjabi
Lang_grn: Guarani
Lang_scn: Sizilianische
Lang_fao: Färöisch
Lang_mri: Maori
Lang_und: Undefined
Lang_ain: Ainu
Lang_san: Sanskrit
Lang_ksh: Kölsch
Lang_nan: Teochew
Lang_roh: Romanisch
Lang_sjn: Sindarin
VocabWelcome: Willkommen bei Vocabtrain
VocabIntroduction: Aufgeregt mit der Stromversorgung des Wortschatzes Trainer mit unzureichender Kontrolle oder schlechten Wortschatz? Dann versuchen Vocabtrain, ein neuer Ansatz der Community getriebene Wortschatz Schöpfung mit Optimierung für asiatische Sprachen (CJK). Statt zu schreiben für jedes Training Buch Alle Vokabeln der Hand (das ist fehleranfällig), können Sie einfach importieren bereits eingelegt Wortschatz aus anderen Bücher (auch mit bereits eingefügten Übersetzungen). Verwenden Sie das Buch-Liste auf der linken zur Navigation.
Hello: hallo
NotAnAdmin: Sie müssen Administrator sein, um diese Seite zugreifen zu können.
WelcomeHomepage: Willkommen auf der Homepage
SeeArchive: Siehe Archiv
NoEntries: Es sind keine Einträge im Blog
LoginToPost: Admins können sich anmelden zu veröffentlichen
NewEntry: Post zu bloggen
NewEntryTitle: Titel
NewEntryContent: Content
PleaseCorrectEntry: Ihre eingereichten Eingabe hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
BookPleaseCorrectEntry: Ihre eingereichten Eingabe hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
EntryCreated title@Text: Ihr neues Blog-Post, #{title}, erstellt wurde
EntryTitle title@Text: Blog Post: #{title}
CommentsHeading: Kommentare
NoComments: Es gibt noch keine Kommentare
AddCommentHeading: Schreibe einen Kommentar
LoginToComment: Sie müssen zum Kommentieren angemeldet sein
AddCommentButton: Kommentar hinzufügen
CommentName: Ihre Anzeige-Namen
CommentText: Kommentar
CommentAdded: Ihr Kommentar wurde hinzugefügt
PleaseCorrectComment: Ihre übermittelten Kommentar hatte einige Fehler, bitte korrigieren und versuchen Sie es erneut.
HomepageTitle: Yesod Blog Demo
BlogArchiveTitle: Blog Archive
